### PR TITLE
Updated Decks

### PR DESCRIPTION
**Pull request by branklam**
Changed naming convention for clarity and readability.
`C<YEAR> - <Name with spaces>.od8`
Added Commander 2015, 2016 and 2017 decks.
Adjusted a Problem with Ixalan Set Probabilities.

My first ever pull request, so be gentle =)

### CODE REVIEW

**Comment by branklam** [comment]
The set fix was Ixalan.  did a scan of other sets to look for same but appear correct.

**Comment by brine** [comment]
appreciate this -- the deck folders have been long neglected.

When I was doing them, I divided the basic lands among the different arts in the set.  Similarly to how they are varied in the IRL products.  It's not really a big deal, TBH it was kinda pain to do it (since online decklists just total up each basic land), but if you wanted to keep it consistent that's what I was doing.

Let me know when you're done with the decks and I'll merge this in.

**Comment by branklam** [comment]
Are you okay with me changing the file names?  It was more of a personal preference.  All the commander decks are updated/ready.  I'll go though and rename/look for missing decks in the other folders as well if you're okay with my naming.

**Comment by brine** [comment]
I was giving it some thought, I think if the deck files get renamed they will be copied over to OCTGN’s deck folder as new files — the old ones won’t be replaced and will be duplicated.  I think we need to keep the naming style intact for the existing files

**Comment by brine** [comment]
Also if we're using set codes to identify the origin of the deck, we should be using the three-letter codes assigned by WotC (C14 for commander 2014, for example)

**Comment by brine** [comment]
sorry for leaving this hanging for so long -- I've recently made some changes to how OCTGN handles decks bundled in the game packages.  It's currently awaiting review: https://github.com/octgn/OCTGN/pull/1764

Once this is pushed live, we should be able to freely make changes to the file names and folder structures without having to worry about the duplication concerns

**Comment by brine** [comment]
I reverted this from master as the required OCTGN updates haven't been pushed out yet, please follow https://github.com/brine/mtg-octgn/tree/updatedecks for the correct branch.

**Pull request merged**
